
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-backstage-prod-diff-credentials.yaml

proxy: null
techdocs: null
auth: null

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    - type: url
      target: https://github.com/Rugvip/backstage-prod-diff/blob/master/data/template/template.yaml
      rules:
      - allow: [Template]
    - type: github-discovery
      target: https://github.com/Rugvip/backstage-*/blob/-/catalog-info.yaml
