version: '3'
services:
  backstage:
    image: backstage
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
    volumes:
      - ./app-config.yaml:/app/app-config.yaml
      - ./app-config.production.yaml:/app/app-config.production.yaml
      - ./github-app-backstage-prod-diff-credentials.yaml:/app/github-app-backstage-prod-diff-credentials.yaml

  catalog:
    image: backstage-catalog
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
    # GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./app-config.catalog.yaml:/app/app-config.yaml
      - ./app-config.production.yaml:/app/app-config.production.yaml
      - ./github-app-backstage-prod-diff-credentials.yaml:/app/github-app-backstage-prod-diff-credentials.yaml

  scaffolder:
    image: backstage-scaffolder
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
    # GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./app-config.scaffolder.yaml:/app/app-config.yaml
      - ./app-config.production.yaml:/app/app-config.production.yaml
      - ./github-app-backstage-prod-diff-credentials.yaml:/app/github-app-backstage-prod-diff-credentials.yaml

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  httpbin:
    image: kennethreitz/httpbin:latest

  proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    command: >-
      --redirect-url=http://localhost:7007/oauth2/callback
      --cookie-secret=${PROXY_COOKIE_SECRET}
      --cookie-secure=false
      --email-domain=*
      --alpha-config=/proxy-config.yaml

    # --http-address=0.0.0.0:4180
    # --provider=github
    # --client-id=${PROXY_GITHUB_CLIENT_ID}
    # --client-secret=${PROXY_GITHUB_CLIENT_SECRET}
    # --set-authorization-header=true
    # --upstream=http://httpbin

    # --upstream=http://backstage:7007
    volumes:
      - './proxy-config.yaml:/proxy-config.yaml'
      - './proxy-client-secret-credentials.yaml:/proxy-client-secret-credentials.yaml'

    hostname: oauth2-proxy
    ports:
      - 7007:4180/tcp
