version: '3'
services:
  backstage:
    image: backstage
    ports:
      - '7007:7007'
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
    volumes:
      - ./app-config.yaml:/app/app-config.yaml
      - ./app-config.production.yaml:/app/app-config.production.yaml
      - ./github-app-backstage-prod-diff-credentials.yaml:/app/github-app-backstage-prod-diff-credentials.yaml

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
