injectRequestHeaders:
- name: X-OAUTH2-PROXY-ID-TOKEN
  values:
  - value: QmVhcmVyIGUzMC5leUp6ZFdJaU9pSlNkV2QyYVhBaWZRLmUzMA==

server:
  BindAddress: 0.0.0.0:4180

upstreamConfig:
  upstreams:
    - id: backstage
      path: /
      uri: http://backstage:7007
    - id: catalog
      path: /api/catalog/
      uri: http://catalog:7007
    - id: httpbin
      path: '^/httpbin/(.*)$'
      rewriteTarget: '/$1'
      uri: http://httpbin

providers:
  - id: github
    provider: github
    clientId: ae98713801ffb8135fab
    clientSecretFile: /proxy-client-secret-credentials.yaml


# {}.{"sub":"Rugvip"}.{}
# Bearer e30.eyJzdWIiOiJSdWd2aXAifQ.e30
# QmVhcmVyIGUzMC5leUp6ZFdJaU9pSlNkV2QyYVhBaWZRLmUzMA==
